<a href="https://colab.research.google.com/github/macrodatascience/100DaysOfCode/blob/main/DataQuest_Linear_Regression_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mounting Google Drive

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [5]:
# Read a file

gdrive_path = '/content/gdrive/MyDrive/Colab Notebooks/'
count=0
with open(f'{gdrive_path}teams.csv', 'r') as file:
  for line in file:
    count+=1
  print(count)

2015


In [9]:
# Write a file

with open(f'{gdrive_path}hello.txt', 'w') as file:
  file.write("Hello Google Drive!")

In [12]:
!cat /content/gdrive/MyDrive/Colab\ Notebooks/hello.txt

Hello Google Drive!

In [14]:
import pandas as pd
import numpy as np

teams = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/teams.csv")

In [15]:
teams.head()

team  year  athletes  events   age  height  weight  prev_medals  medals
0  AFG  1964         8       8  22.0   161.0    64.2          0.0       0
1  AFG  1968         5       5  23.2   170.2    70.0          0.0       0
2  AFG  1972         8       8  29.0   168.3    63.8          0.0       0
3  AFG  1980        11      11  23.6   168.4    63.2          0.0       0
4  AFG  2004         5       5  18.6   170.8    64.8          0.0       0

In [17]:
teams.shape

(2014, 9)

In [18]:
teams.describe()

year     athletes       events          age       height  \
count  2014.000000  2014.000000  2014.000000  2014.000000  2014.000000   
mean   1995.227408    76.329692    36.877855    24.812612   173.955164   
std      15.227727   129.799427    50.130877     2.758258     5.262469   
min    1964.000000     1.000000     1.000000    17.000000   151.000000   
25%    1984.000000     7.000000     6.000000    23.300000   170.600000   
50%    1996.000000    21.000000    14.000000    24.700000   174.400000   
75%    2008.000000    74.750000    47.000000    26.100000   177.300000   
max    2016.000000   839.000000   270.000000    66.000000   193.000000   

            weight  prev_medals       medals  
count  2014.000000  2014.000000  2014.000000  
mean     69.328997    10.248759    10.990070  
std       7.494740    31.951920    33.627528  
min      43.300000     0.000000     0.000000  
25%      64.700000     0.000000     0.000000  
50%      69.500000     0.000000     0.000000  
75%      73.400000     4.000000     5.000000  
max     148.000000   442.000000   442.000000

In [19]:
teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2014 entries, 0 to 2013
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   team         2014 non-null   object 
 1   year         2014 non-null   int64  
 2   athletes     2014 non-null   int64  
 3   events       2014 non-null   int64  
 4   age          2014 non-null   float64
 5   height       2014 non-null   float64
 6   weight       2014 non-null   float64
 7   prev_medals  2014 non-null   float64
 8   medals       2014 non-null   int64  
dtypes: float64(4), int64(4), object(1)
memory usage: 141.7+ KB


In [44]:
# X = teams[["athletes", "prev_medals"]].copy()
# y = teams[["medals"]].copy()

X = teams[["athletes", "prev_medals"]]
y = teams[["medals"]]

In [45]:
X.shape, y.shape

((2014, 2), (2014, 1))

In [46]:
teams.shape, y.shape

((2014, 9), (2014, 1))

In [47]:
# X["intercept"] = 1
X["intercept"] = 1
X = X[["intercept","athletes", "prev_medals"]]
X.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


(2014, 3)

In [48]:
# Transpose of X

X_T = X.T

In [49]:
X_T.shape, X.shape, y.shape

((3, 2014), (2014, 3), (2014, 1))

In [73]:
B = np.linalg.inv(X_T @ X) @ X_T @ y
B.index = X.columns
B

medals
intercept   -1.961889
athletes     0.071112
prev_medals  0.734137

In [74]:
X.shape, B.shape, type(X), type(B)

((2014, 3), (3, 1), pandas.core.frame.DataFrame, pandas.core.frame.DataFrame)

In [78]:
predictions = X@B
predictions

medals
0    -1.392992
1    -1.606329
2    -1.392992
3    -1.179656
4    -1.606329
...        ...
2009 -0.112974
2010 -0.966319
2011  1.378315
2012  1.614667
2013  0.242587

[2014 rows x 1 columns]

In [76]:
np.matrix(X) * np.matrix(B)

matrix([[-1.39299224],
        [-1.60632867],
        [-1.39299224],
        ...,
        [ 1.3783153 ],
        [ 1.61466709],
        [ 0.24258707]])

In [77]:
np.linalg.multi_dot([X,B])

array([[-1.39299224],
       [-1.60632867],
       [-1.39299224],
       ...,
       [ 1.3783153 ],
       [ 1.61466709],
       [ 0.24258707]])

In [80]:
# Sum of Squared Residuals

SSR = ((y - predictions)**2).sum()

In [81]:
# Sum of squared totals

SST = ((y - y.mean())**2).sum()

In [82]:
SSR, SST

(medals    290620.124598
 dtype: float64, medals    2.276322e+06
 dtype: float64)

In [83]:
SSR/SST

medals    0.127671
dtype: float64

In [84]:
r_squared = 1 - SSR/SST
r_squared

medals    0.872329
dtype: float64

In [85]:
from sklearn.linear_model import LinearRegression

In [86]:
lr = LinearRegression()
lr.fit(teams[["athletes", "prev_medals"]], teams[["medals"]])

LinearRegression()

In [87]:
lr.intercept_

array([-1.96188939])

In [89]:
lr.coef_

array([[0.07111214, 0.73413679]])

In [90]:
B

medals
intercept   -1.961889
athletes     0.071112
prev_medals  0.734137